### ISSUE TITLE
invalid redirect url

### ISSUE THREAD

**Issue by felix288** [s0mnaths/Music-Party#1]
am trying to run and getting this 

INVALID_CLIENT: Invalid redirect URI

**Comment by s0mnaths** [comment]
I'm sorry for the late reply.

https://community.spotify.com/t5/Spotify-for-Developers/INVALID-CLIENT-Invalid-redirect-URI/td-p/5228936
Have you tried going through this? If this doesn't fix it, I'll try itmyself and let you know

**Comment by felix288** [comment]
Ah yes I have tried that and no luck if you could have a look that would be great

**Comment by felix288** [comment]
could you have a look please

**Comment by s0mnaths** [comment]
Fixed it. According to new docs the redirect URI needs to be exactly the same as what we mentioned in `spotify/credentials.py`. 
Therefore in our spotify app in [Developer Dashboard](https://developer.spotify.com/dashboard) our redirect URI would be `"http://127.0.0.1:8000/spotify/redirect"` . 

Updated the readme, hope it helps.
